# Generated by Django 6.0.6 on 2026-06-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ikonex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradescale',
            old_name='max_core',
            new_name='max_score',
        ),
    ]
