from django.http import HttpResponse
from reportlab.pdfgen import canvas
from django.shortcuts import get_object_or_404

from .models import Student, Assessment, ClassStream
from .utils import average_score, determine_grade


def student_report_card_pdf(request, student_id):

    student = get_object_or_404(Student, id=student_id)

    class_stream = student.class_stream

    # Get all students in class for ranking
    class_students = Student.objects.filter(class_stream=class_stream)

    ranked = []

    for s in class_students:
        avg = average_score(s)
        ranked.append({
            "student": s,
            "average": avg
        })

    ranked.sort(key=lambda x: x["average"], reverse=True)

    
    rank = next(
        (i + 1 for i, item in enumerate(ranked)
         if item["student"].id == student.id),
        None
    )

    assessments = Assessment.objects.filter(student=student)

    avg_score = average_score(student)
    grade = determine_grade(avg_score)

    
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{student.admission_number}_report_card.pdf"'

    p = canvas.Canvas(response)

    y = 800

   
    p.setFont("Helvetica-Bold", 18)
    p.drawString(180, y, "STUDENT REPORT CARD")

    y -= 40

    
    p.setFont("Helvetica", 12)

    full_name = f"{student.surname} {student.first_name} {student.last_name}"

    p.drawString(50, y, f"Name: {full_name}")
    y -= 20

    p.drawString(50, y, f"Admission Number: {student.admission_number}")
    y -= 20

    p.drawString(50, y, f"Class: {class_stream}")
    y -= 20

    p.drawString(50, y, f"Rank in Class: #{rank}")
    y -= 20

    p.drawString(50, y, f"Average Score: {round(avg_score, 2)}")
    y -= 20

    p.drawString(50, y, f"Grade: {grade}")
    y -= 40

   
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, y, "Subject")
    p.drawString(200, y, "CAT")
    p.drawString(300, y, "Exam")
    p.drawString(400, y, "Total")

    y -= 20
    p.line(50, y, 500, y)
    y -= 20

   
    p.setFont("Helvetica", 11)

    for a in assessments:

        total = a.cat_score + a.exam_score

        p.drawString(50, y, str(a.subject.name))
        p.drawString(200, y, str(a.cat_score))
        p.drawString(300, y, str(a.exam_score))
        p.drawString(400, y, str(total))

        y -= 20

        # page break safety
        if y < 120:
            p.showPage()
            y = 800

   
    y -= 30
    p.setFont("Helvetica-Oblique", 10)
    p.drawString(50, y, "Generated by Ikonex Academy System")

    p.save()

    return response